version: '3.9'

services:
  web:
    build: .
    depends_on:
      - db_postgres
    volumes:
      - .:/usr/src/code
      - static_volume:/usr/src/code/static
      - media_volume:/usr/src/code/media
    env_file:
      - ./.env.dev
    command: gunicorn tify.wsgi:application --bind 0.0.0.0:8000
    networks:
      - nginx_network
      - postgres_network
  nginx:
    build:
      context: ./Dockerfiles/nginx
      dockerfile: Dockerfile
    ports:
      - 8000:80
    depends_on:
      - web
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/usr/src/code/static
      - media_volume:/usr/src/code/media
    networks:
      - nginx_network
  db_postgres:
    build:
      context: ./Dockerfiles/postgres
      dockerfile: Dockerfile
    env_file:
      - ./.env.dev.db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
networks:
  nginx_network:
    driver: bridge
  postgres_network:
    driver: bridge
volumes:
  postgres_data:
  static_volume:
  media_volume:
