# Generated by Django 3.2.16 on 2022-11-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_url_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url_hash',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
